name: Build macOS

on: [push]

env:
  PROJECT_NAME: PROJECT_TEMPLATE_PLACEHOLDER

jobs:

  build:
 
    runs-on: macos-latest
 
    steps:

    - name: Checkout iPlug2
      uses: actions/checkout@v2
      with:
        repository: iPlug2/iPlug2
        path: iPlug2

    - name: Check out repository
      uses: actions/checkout@v2
      with:
        path: iPlug2/Projects/${{env.PROJECT_NAME}}

    - name: Get VST3_SDK
      run: |
        cd iPlug2/Dependencies/IPlug
        ./download-iplug-libs.sh
      shell: bash

    - name: Get Prebuilt Libs
      run: |
        cd iPlug2/Dependencies
        ./download-prebuilt-libs.sh
      shell: bash

    - name: Build it
      run: |
        cd iPlug2/Projects/${{env.PROJECT_NAME}}/scripts
        ./makedist-mac.sh
      shell: bash

    - name: Move files
      run: |
        mkdir -p iPlug2/Projects/${{env.PROJECT_NAME}}/build-mac/zip
        mv iPlug2/Projects/${{env.PROJECT_NAME}}/installer/*.zip iPlug2/Projects/${{env.PROJECT_NAME}}/build-mac/zip
        mv iPlug2/Projects/${{env.PROJECT_NAME}}/installer/*.dmg iPlug2/Projects/${{env.PROJECT_NAME}}/build-mac/zip
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{env.PROJECT_NAME}}-mac
        path: iPlug2/Projects/${{env.PROJECT_NAME}}/build-mac/zip
