name: Build Windows

on: [push]

env:
  PROJECT_NAME: PROJECT_TEMPLATE_PLACEHOLDER

jobs:

  build:
 
    runs-on: windows-latest
 
    steps:

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Checkout iPlug2
      uses: actions/checkout@v2
      with:
        repository: iPlug2/iPlug2
        path: iPlug2

    - name: Check out repository
      uses: actions/checkout@v2
      with:
        path: iPlug2/Projects/${{env.PROJECT_NAME}}

    - name: Get VST3_SDK
      run: |
        cd iPlug2/Dependencies/IPlug
        ./download-iplug-libs.sh
      shell: bash

    - name: Get Prebuilt Libs
      run: |
        cd iPlug2/Dependencies
        ./download-prebuilt-libs.sh
      shell: bash

    - name: Build it
      run: |
        cd iPlug2\Projects\${{env.PROJECT_NAME}}\scripts
        .\makedist-win.bat 0
      shell: pwsh

    - name: Move pdb files
      run: |
        mv iPlug2/Projects/${{env.PROJECT_NAME}}/build-win/pdbs/*.pdb iPlug2/Projects/${{env.PROJECT_NAME}}/build-win/zip/
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{env.PROJECT_NAME}}-win
        path: iPlug2\Projects\${{env.PROJECT_NAME}}\build-win\zip
